version: '3'

services:
  my_app:
    build:
      context: .
      dockerfile: marioBros1
    runtime: nvidia
    volumes:
      - /mnt/nvme0/models:/app/models
      - /mnt/nvme0/logs:/app/logs
    ports:
      - "8080:80"
