version: '3.8'

services:
  my_app_1:
    build:
      context: .
      dockerfile: marioBros1
    runtime: nvidia
    volumes:
      - /mnt/nvme0/models:/app/models
      - /mnt/nvme0/logs:/app/logs_1  # Different log directory for each instance
    ports:
      - "8081:80"  # Different host port for each instance

  my_app_2:
    build:
      context: .
      dockerfile: marioBros1
    runtime: nvidia
    volumes:
      - /mnt/nvme0/models:/app/models
      - /mnt/nvme0/logs:/app/logs_2  # Different log directory for each instance
    ports:
      - "8082:80"  # Different host port for each instance

# Add more services (my_app_3, my_app_4, etc.) following the same pattern if needed.
